<table>
    
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Care Center</th>
        <th>Laboratory</th>
        
    </tr>
    <tr>
    <?php 
    
    foreach ($this->tech as $key => $value) {
        
        echo '<tr><td>' . $value['first_name'] . '</td>';
        echo '<td>' . $value['last_name'] . '</td>';
        echo '<td>' . $value['name'] . '</td>';
        echo '<td>' . $value['laboratory_name'] . '</td></tr>';
    }
    
    
     ?>
    </tr>
    
</table>

