
<h2>Technicians</h2>
<div id="spacer">
<table>
    
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Care Center</th>
        <th>Laboratory</th>
        
    </tr>
    <?php
    $count = 0;
     
    foreach ($this->tech as $key => $value) {
        $count++;
            if ($count & 1) {
                ?> <tr class="d0"> <?php
        } else {
                ?><tr id="d1"> <?php
        }
     
        echo '<td>' . $value['first_name'] . '</td>';
        echo '<td>' . $value['last_name'] . '</td>';
        echo '<td>' . $value['name'] . '</td>';
        echo '<td>' . $value['laboratory_name'] . '</td>';
    }
    
    
     ?>
    </tr>
    
</table>
</div>
