
<table border="0" align="center">
    <tr>      
        <th>Specialty</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Address</th>
        <?php echo $this->form; ?>
    </tr>
    <?php
    if (isset($this->person)) {
        foreach ($this->person as $key => $value) {
            ?> <tr id="row_<?php //echo $value['firstName'];     ?>">
                <?php
                echo '<tr>';
                echo '<td>' . $value['specialty'] . '</td>';
                $myVar = $value['physician'];
                ?>

                <td><?php echo $myVar['firstName']; ?></td>
                <td><?php echo $myVar['lastName']; ?></td>
                <td><?php echo $myVar['address']; ?></td>
            </tr>
        <?php }
    } ?>

</table>
