
<div id="centerContent">
<h2>Medds Heath Care Centre</h2>



    <table>
        <tr>
            <td>

                Welcome to Medds Health Care Centre

                Celebrating 100 years of hospital care from 1912 to 2012. 
                Medds Health Care Centre operates an 87-bed acute and complex continuing care facility and offering outpatient services including diabetes education, x-ray, and speech-language pathology. 

                Medds Health Care Centre serves more than 135,000 residents in The City of Nanaimo, British Columbia.
            </td>
        </tr>

    </table>
   
</div>