<?php

$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Care Center');

?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
<!--     <script type='text/javascript' src='http://code.jquery.com/jquery-1.4.4.min.js'></script>-->

          <script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery-1.4.4.min.js') ?>" ></script>
         
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery.easing.1.3.js') ?>"></script> 
         <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/jquery.ennui.contentslider.css'); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/jquery.ennui.contentslider.css'); ?>
    
     
  

             
                    <script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery.qtip.js') ?>" ></script>
                     
          <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/jquery.qtip.css'); ?>
 <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery.qtip-1.0.0-rc3.min.js') ?>"></script> 
        
<?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/index.css'); ?>

    
<!--    
      <script type='text/javascript' src="http://craigsworks.com/projects/qtip_new/packages/nightly/jquery.qtip.js"></script>-->

<!--    
      <link rel="stylesheet" type="text/css" href="http://craigsworks.com/projects/qtip_new/packages/nightly/jquery.qtip.css"/>-->
  
        

    </head>
 
    <body>
        
     
              <div id="content" >
                    
                   <div id="headerimage" align="center"  >
           <img src="<?php echo $this->baseUrl('images/MEDDS.png') ?>" alt="MEDDS header background image" />    </div>
                  
      <div id="toprightholder"><?php echo $this->loggedInAs(); ?></div>
     
            <div id="navigation" class="nav">
                <?php echo $this->navigation()->menu(); ?>
            </div> 
                    
<!--                   <div id="leftholder">
                <?php 
//                  echo "</br>";
//                echo "stuff goes here"; 
//                echo "</br>";
//                echo "</br>";
//                echo "emergencyz";
//                  echo "</br>";
//                    echo "</br>";
                ?>
            </div>  -->
                
            <?php echo $this->layout()->content;  ?>
       
              <div class="clearfooter"></div>      
                           
               <div id="footer">            
           site designed by MEDDS
        </div>
              </div>
     
    </body> 
     
    
</html>    
    
  