<?php

$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Care Center');
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/index.css'); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/jquery.ennui.contentslider.css'); ?>

        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery-1.4.2.min.js') ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery.easing.1.3.js') ?>"></script> 
        <script type="text/javascript" src="<?php echo $this->baseUrl('https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js') ?>"></script> 

    </head>
 
    <body>
        
     
              <div id="content">
                   <div id="headerimage" align="center" padding="202px" >
           <img src="<?php echo $this->baseUrl('images/MEDDS.png') ?>" alt="MEDDS header background image" width="1000" height="142" />
           </div>
        <div id="toprightholder"><?php echo $this->loggedInAs(); ?></div>
     
            <div id="navigation" class="nav">
                <?php echo $this->navigation()->menu(); ?>
            </div> 
                      <div id="leftholder">
                <?php 
                  echo "</br>";
                echo "stuff goes here"; 
                echo "</br>";
                echo "</br>";
                echo "emergencyz";
                  echo "</br>";
                    echo "</br>";
                ?>
            </div>  
                
                        
                       <div id="rightholder">
                <?php echo $this->navigation()->menu(); ?>
                          </div>
                     
                        <?php echo $this->layout()->content; ?>
                  
           <footer> 
            
           <p>All content &copy; 2011 R2Autos. site designed by MEDDS</p>
        </footer> 
            </div>     
        

  
            
       
    </body> 
         
    
  